fix: bump typescript version to resolve type errors
This also bumps fork-ts-checker-webpack-plugin to resolve a peer dependency
warning. This is because fork-ts-checker-webpack-plugin@0.5.2" has peer
dependency "typescript@^2.1.0 || ^3.0.0".

Errors were:
ERROR in /Users/joey/dev/flux-labs/blog-demos/add-jest-to-apollo-app/src/server.ts(17,23):
TS2339: Property 'url' does not exist on type 'Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>>'.
ERROR in /Users/joey/dev/flux-labs/blog-demos/add-jest-to-apollo-app/src/server.ts(17,44):
TS2339: Property 'url' does not exist on type 'Request<ParamsDictionary, any, any, ParsedQs, Record<string, any>>'.
ERROR in /Users/joey/dev/flux-labs/blog-demos/add-jest-to-apollo-app/src/server.ts(20,13):
TS2339: Property 'setHeader' does not exist on type 'Response<any, Record<string, any>>'.
ERROR in /Users/joey/dev/flux-labs/blog-demos/add-jest-to-apollo-app/src/server.ts(21,13):
TS2339: Property 'write' does not exist on type 'Response<any, Record<string, any>>'.
ERROR in /Users/joey/dev/flux-labs/blog-demos/add-jest-to-apollo-app/src/server.ts(22,13):
TS2339: Property 'end' does not exist on type 'Response<any, Record<string, any>>'.